# Key bindings for taking screenshots
#
# The image files will be written to XDG_SCREENSHOTS_DIR if this is set
# or defined in user-dirs.dir, or to a fallback location XDG_PICTURES_DIR.
#
# Copy the file to ~/.config/sway/config.d/60-bindings-screenshot.conf (or to
# your $XDG_CONFIG_HOME location if set differently) to be able to overwrite
# existing shortcuts.
# Check 'man grimshot' for additional commands that you may find useful.
#
# Requires:     grimshot

bindsym {
    # Active output: Print = clipboard, Shift+Print = file
    Print           exec grimshot copy output
    Shift+Print     exec env XDG_SCREENSHOTS_DIR=$HOME/Downloads grimshot save output
    # Active window: Alt+Print = clipboard, Alt+Shift+Print = file
    Alt+Print       exec grimshot copy active
    Alt+Shift+Print exec env XDG_SCREENSHOTS_DIR=$HOME/Downloads grimshot save active
    # Custom area: Ctrl+Print = clipboard, Ctrl+Shift+Print = file
    Ctrl+Print      exec grimshot copy area
    Ctrl+Shift+Print exec env XDG_SCREENSHOTS_DIR=$HOME/Downloads grimshot save area
}
